name = "LeafGasExchange"
uuid = "eed59905-05f1-464e-afba-94c39a4505fd"
authors = ["Kyungdahm Yun <tomyun@gmail.com>"]
version = "0.1.3-DEV"

[deps]
Cropbox = "a904b226-abf1-11e9-2713-059ba252a964"

[compat]
Cropbox = "0.3"
julia = "1.6"
