name = "LeafGasExchange"
uuid = "eed59905-05f1-464e-afba-94c39a4505fd"
authors = ["Kyungdahm Yun <tomyun@gmail.com>"]
version = "0.1.7-DEV"

[deps]
Cropbox = "a904b226-abf1-11e9-2713-059ba252a964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Cropbox = "0.3"
julia = "1.6"
