name: test
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        version: ['1']
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64]
        experimental: [false]
        include:
          - version: 'nightly'
            os: macos-latest
            arch: x64
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        with:
          depwarn: error
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v1
